### ISSUE TITLE
Tabs requires section as pane to work.

### ISSUE THREAD

**Issue by JimBobSquarePants** [ResponsiveBP/Responsive#10]
``` css
    [data-tabs] > ul,
    [data-tabs] > section.tab-pane-active {
        display: block;
    }
```

Should be

``` css
    [data-tabs] > ul,
    [data-tabs] > .tab-pane-active {
        display: block;
    }
```
