### ISSUE TITLE
Lightbox scrolling on win phone 8

### ISSUE THREAD

**Issue by JimBobSquarePants** [ResponsiveBP/Responsive#17]
On the Nokia Lumia 925 the lightbox can scroll outwith the range of the overlay.

``` css
.lightbox-on {
    -ms-touch-action: none;
    touch-action: none;
}
```

Will fix it whilst allowing child interaction to continue as normal.
