### ISSUE TITLE
Media layout is incorrect

### ISSUE THREAD

**Issue by JimBobSquarePants** [ResponsiveBP/Responsive#2]
Media layout for youtube and vimeo is incorrect.

padding should be:

``` css
.media {
    padding: 30px 0 56.25%;
}

.media.vimeo {
    padding-top: 0;
}
```
