### ISSUE TITLE
Left margin not removed on adjacent 12-column elements

### ISSUE THREAD

**Issue by mphillips** [ResponsiveBP/Responsive#23]
Using v2.5.3

When two adjacent 12-column elements exist in a row, the left margin isn't removed on the second one.

This issue exists for the following column sizes:

col-s-12 
col-m-12 
col-l-12

Here is the HTML:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Your site description." />
    <title>Your page title</title>

    <script src="responsive.ie10mobilefix.min.js"></script>
    <link href="responsive.css" rel="stylesheet" />

    <!--[if lt IE 9 &!(IEMobile)]>
        <script src="vendor/html5shiv.min.js"></script>
        <script src="vendor/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-s-12 col-m-12 col-l-12" style="background: red;
    height:100px">
                col-xs-12 col-s-12 col-m-8
            </div>

            <div class="col-xs-12 col-s-12 col-m-12 col-l-12" style="background: red;
    height: 100px;">
                col-xs-12 col-s-12 col-m-4
            </div>
        </div>
    </div>

    <!--[if IE 8]>
    <script src="vendor/jquery-1.11.0.min.js"></script>
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <script src="vendor/jquery-2.1.0.min.js"></script>
    <!--<![endif]-->

    <script src="responsive.min.js"></script>
</body>
</html>
```

Renders like this:

![screen shot 2014-04-14 at 11 08 49 am](https://cloud.githubusercontent.com/assets/18812/2696780/bb8469d0-c3e6-11e3-8c45-4bf6b3330246.png)

The problem seems to be this style (and the similar ones for each column size listed above):

``` css
.row [class*="col-"] + [class*="col-s"] {
    margin-left: 2%;
}
```

takes precedence over this one:

``` css
.col-s-12 {
    width: 100%;
    margin-left: 0;
}
```

You can fix it changing the latter to this:

``` css
.row [class*="col-"] + [class*="col-s-12"],
.col-s-12 {
    width: 100%;
    margin-left: 0;
}
```

I would have done a pull request but you may know a better way to fix this.

Thanks!
